config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'tasks', to: 'tasks#index', as: 'tasks'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'

  post 'tasks', to: 'tasks#create'

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit your task here</h1>
  <%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="text-center">My tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
    <li class="text-decoration-none list-group-item">
       <% if task.completed == true %>
          <img src="https://img.icons8.com/metro/26/000000/checked-checkbox.png">
        <% else %>
          <img src="https://img.icons8.com/metro/26/000000/unchecked-checkbox.png">
        <% end %> |
       <%= link_to task_path( task['id'] ) do %>
       <%= task.title %>
       <% end %>  |
       <%= link_to task_path(task),
        method: :delete,
        data: { confirm: "Are you sure to delete this task?" } do %>
        <img src="https://img.icons8.com/windows/50/000000/delete-forever.png" width="20">
        <% end %>
    </li>
    <% end %>
  </ul>
  <div class="d-flex justify-content-center">
  <%= link_to '+ create a new task', tasks_new_path, :class=>"btn btn-primary" %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
<h1>Add a new task here</h1>
 <%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <p><%= @task.completed %></p>
  <p><%= link_to 'edit this tasks', edit_task_path(params[:id]) %></p>
  <p><%= link_to '<< back to tasks', tasks_path %></p>
</div>